{
    "code": 0,
    "data": {
        "id": 5,
        "name": "博拉科技",
        "type": 0,
        "icon": "",
        "createTime": "2019-10-08 13:10:25",
        "isDelete": 1,
        "modifyTime": "2019-12-02 09:32:42",
        "clientType": 0,
        "childMenu": [
            {
                "id": 9,
                "parentId": 5,
                "name": "商业智能",
                "type": 0,
                "icon": "",
                "createTime": "2019-12-02 16:34:32",
                "isDelete": 1,
                "modifyTime": "2019-12-02 16:34:32",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 106,
                        "parentId": 9,
                        "name": "经营驾驶舱",
                        "type": 1,
                        "createTime": "2019-12-02 16:37:41",
                        "isDelete": 1,
                        "modifyTime": "2019-12-02 16:38:31",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 220,
                        "parentId": 9,
                        "name": "BI看板二",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-04-03 15:50:53",
                        "isDelete": 1,
                        "modifyTime": "2020-04-03 15:50:53",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 221,
                        "parentId": 9,
                        "name": "BI看板三",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-04-03 15:51:08",
                        "isDelete": 1,
                        "modifyTime": "2020-04-03 15:51:08",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 10,
                "parentId": 5,
                "name": "知识图谱",
                "type": 0,
                "icon": "",
                "createTime": "2019-10-08 15:18:15",
                "isDelete": 1,
                "modifyTime": "2019-11-23 11:16:45",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 22,
                        "parentId": 10,
                        "name": "工厂建模",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:23:39",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 23,
                        "parentId": 10,
                        "name": "物料定义",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:24:00",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 24,
                        "parentId": 10,
                        "name": "BOM定义",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:24:11",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 25,
                        "parentId": 10,
                        "name": "设备定义",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:24:24",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 26,
                        "parentId": 10,
                        "name": "工序定义",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:24:35",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 27,
                        "parentId": 10,
                        "name": "工艺参数",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:24:57",
                        "isDelete": 1,
                        "modifyTime": "2019-12-04 14:18:17",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 29,
                        "parentId": 10,
                        "name": "产能定义",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:25:20",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 30,
                        "parentId": 10,
                        "name": "工厂日历",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:25:31",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 31,
                        "parentId": 10,
                        "name": "终端定义",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:25:41",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 104,
                        "parentId": 10,
                        "name": "工艺路线",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-11-23 13:49:09",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 13:49:09",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 114,
                        "parentId": 10,
                        "name": "仓库定义",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-12-11 13:40:55",
                        "isDelete": 1,
                        "modifyTime": "2019-12-11 13:40:55",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 117,
                        "parentId": 10,
                        "name": "工价定义",
                        "type": 0,
                        "icon": "",
                        "createTime": "2019-12-16 14:28:31",
                        "isDelete": 1,
                        "modifyTime": "2019-12-16 14:28:31",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 118,
                        "parentId": 10,
                        "name": "工价定义",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-12-18 11:10:57",
                        "isDelete": 1,
                        "modifyTime": "2019-12-18 11:10:57",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 121,
                        "parentId": 10,
                        "name": "客户定义",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-12-18 15:55:29",
                        "isDelete": 1,
                        "modifyTime": "2019-12-18 15:55:29",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 122,
                        "parentId": 10,
                        "name": "供应商定义",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-12-18 15:55:40",
                        "isDelete": 1,
                        "modifyTime": "2019-12-18 15:55:40",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 124,
                        "parentId": 10,
                        "name": "原因定义",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-12-23 18:51:46",
                        "isDelete": 1,
                        "modifyTime": "2019-12-23 18:51:46",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 185,
                        "parentId": 10,
                        "name": "规则配置",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-02-28 16:16:07",
                        "isDelete": 1,
                        "modifyTime": "2020-02-28 16:16:07",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 186,
                        "parentId": 10,
                        "name": "规则配置",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-02-28 16:16:08",
                        "isDelete": 1,
                        "modifyTime": "2020-02-28 16:16:08",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 187,
                        "parentId": 10,
                        "name": "规则配置",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-02-28 16:16:08",
                        "isDelete": 1,
                        "modifyTime": "2020-02-28 16:16:08",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 188,
                        "parentId": 10,
                        "name": "数据字典",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-02-28 17:00:04",
                        "isDelete": 1,
                        "modifyTime": "2020-02-28 17:00:04",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 208,
                        "parentId": 10,
                        "name": "APS制造BOM定义",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-03-25 17:51:23",
                        "isDelete": 1,
                        "modifyTime": "2020-03-25 17:51:23",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 216,
                        "parentId": 10,
                        "name": "甘特图",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-04-01 16:40:59",
                        "isDelete": 1,
                        "modifyTime": "2020-04-01 16:40:59",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 11,
                "parentId": 5,
                "name": "设备管理",
                "type": 0,
                "icon": "",
                "createTime": "2019-10-08 15:18:31",
                "isDelete": 1,
                "modifyTime": "2019-11-23 11:16:45",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 33,
                        "parentId": 11,
                        "name": "设备监控",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:26:12",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 34,
                        "parentId": 11,
                        "name": "设备维保",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:26:21",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 35,
                        "parentId": 11,
                        "name": "运维工单",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:26:31",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 36,
                        "parentId": 11,
                        "name": "设备分析",
                        "type": 1,
                        "createTime": "2019-12-02 09:49:39",
                        "isDelete": 1,
                        "modifyTime": "2019-12-02 09:49:39",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 105,
                        "parentId": 11,
                        "name": "备件管理",
                        "type": 1,
                        "createTime": "2019-12-02 11:01:05",
                        "isDelete": 1,
                        "modifyTime": "2019-12-02 11:01:05",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 130,
                        "parentId": 11,
                        "name": "维保分析",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-12-27 11:23:42",
                        "isDelete": 1,
                        "modifyTime": "2019-12-27 11:23:42",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 131,
                        "parentId": 11,
                        "name": "异常统计",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-01-06 14:24:10",
                        "isDelete": 1,
                        "modifyTime": "2020-01-06 14:24:10",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 137,
                        "parentId": 11,
                        "name": "工单派发",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-01-08 09:41:45",
                        "isDelete": 1,
                        "modifyTime": "2020-01-08 09:41:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 138,
                        "parentId": 11,
                        "name": "运维日志",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-01-08 09:42:02",
                        "isDelete": 1,
                        "modifyTime": "2020-01-08 09:42:02",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 195,
                        "parentId": 11,
                        "name": "设备台账",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-03-12 16:38:48",
                        "isDelete": 1,
                        "modifyTime": "2020-03-12 16:38:48",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 222,
                        "parentId": 11,
                        "name": "维修报告",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-04-13 14:07:12",
                        "isDelete": 1,
                        "modifyTime": "2020-04-13 14:07:12",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 226,
                        "parentId": 11,
                        "name": "设备切片",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-06-19 10:59:43",
                        "isDelete": 1,
                        "modifyTime": "2020-06-19 10:59:43",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 227,
                        "parentId": 11,
                        "name": "切片分析",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-06-19 11:00:01",
                        "isDelete": 1,
                        "modifyTime": "2020-06-19 11:00:01",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 229,
                        "parentId": 11,
                        "name": "产量统计",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-07-30 11:23:53",
                        "isDelete": 1,
                        "modifyTime": "2020-07-30 11:23:53",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 230,
                        "parentId": 11,
                        "name": "节拍统计",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-07-30 11:24:08",
                        "isDelete": 1,
                        "modifyTime": "2020-07-30 11:24:08",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 12,
                "parentId": 5,
                "name": "计划管理",
                "type": 0,
                "icon": "",
                "createTime": "2019-10-08 15:18:54",
                "isDelete": 1,
                "modifyTime": "2019-11-23 11:16:45",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 38,
                        "parentId": 12,
                        "name": "制造订单",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:27:24",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 39,
                        "parentId": 12,
                        "name": "排程预测",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:27:35",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 40,
                        "parentId": 12,
                        "name": "高级排程",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:27:44",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 228,
                        "parentId": 12,
                        "name": "生产任务",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-06-28 09:25:16",
                        "isDelete": 1,
                        "modifyTime": "2020-06-28 09:25:16",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 231,
                        "parentId": 12,
                        "name": "联合排程",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-11-11 22:05:28",
                        "isDelete": 1,
                        "modifyTime": "2020-11-11 22:05:28",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 13,
                "parentId": 5,
                "name": "生产管理",
                "type": 0,
                "icon": "",
                "createTime": "2019-10-08 15:19:18",
                "isDelete": 1,
                "modifyTime": "2019-11-23 11:16:45",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 42,
                        "parentId": 13,
                        "name": "工单管理",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:28:24",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 43,
                        "parentId": 13,
                        "name": "生产报工",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:28:32",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 44,
                        "parentId": 13,
                        "name": "生产分析",
                        "type": 1,
                        "createTime": "2019-12-02 09:40:36",
                        "isDelete": 1,
                        "modifyTime": "2019-12-02 09:40:36",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 132,
                        "parentId": 13,
                        "name": "生产进度",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-01-06 14:25:30",
                        "isDelete": 1,
                        "modifyTime": "2020-01-06 14:25:30",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 134,
                        "parentId": 13,
                        "name": "履历查询",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-01-06 14:27:35",
                        "isDelete": 1,
                        "modifyTime": "2020-01-06 14:27:35",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 135,
                        "parentId": 13,
                        "name": "产量统计",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-01-06 14:28:33",
                        "isDelete": 1,
                        "modifyTime": "2020-01-06 14:28:33",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 139,
                        "parentId": 13,
                        "name": "库存波动",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-01-09 09:51:33",
                        "isDelete": 1,
                        "modifyTime": "2020-01-09 09:51:33",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 196,
                        "parentId": 13,
                        "name": "生产报表",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-03-13 11:08:59",
                        "isDelete": 1,
                        "modifyTime": "2020-03-13 11:08:59",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 14,
                "parentId": 5,
                "name": "质量管理",
                "type": 0,
                "icon": "",
                "createTime": "2019-10-08 15:19:29",
                "isDelete": 1,
                "modifyTime": "2019-11-23 11:16:45",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 45,
                        "parentId": 14,
                        "name": "质检配置",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:29:07",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 46,
                        "parentId": 14,
                        "name": "结果查询",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:29:16",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 47,
                        "parentId": 14,
                        "name": "质量分析",
                        "type": 1,
                        "createTime": "2019-12-02 09:42:28",
                        "isDelete": 1,
                        "modifyTime": "2019-12-02 09:43:27",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 197,
                        "parentId": 14,
                        "name": "SPC分析",
                        "type": 0,
                        "icon": "",
                        "createTime": "2020-03-13 15:18:36",
                        "isDelete": 1,
                        "modifyTime": "2020-03-13 15:18:36",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 15,
                "parentId": 5,
                "name": "异常响应",
                "type": 0,
                "icon": "",
                "createTime": "2019-10-08 15:19:52",
                "isDelete": 1,
                "modifyTime": "2019-11-23 11:16:45",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 49,
                        "parentId": 15,
                        "name": "异常定义",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:29:50",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 50,
                        "parentId": 15,
                        "name": "异常呼叫",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:29:59",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 51,
                        "parentId": 15,
                        "name": "结果查询",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:30:09",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 103,
                        "parentId": 15,
                        "name": "异常分析",
                        "type": 1,
                        "createTime": "2019-12-03 10:08:19",
                        "isDelete": 1,
                        "modifyTime": "2019-12-03 10:08:19",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 16,
                "parentId": 5,
                "name": "图文管理",
                "type": 1,
                "icon": "",
                "createTime": "2019-10-08 15:20:03",
                "isDelete": 1,
                "modifyTime": "2019-11-23 11:16:45",
                "clientType": 0,
                "childMenu": []
            },
            {
                "id": 17,
                "parentId": 5,
                "name": "工具管理",
                "type": 0,
                "icon": "",
                "createTime": "2019-10-08 15:20:15",
                "isDelete": 1,
                "modifyTime": "2019-11-23 11:16:45",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 52,
                        "parentId": 17,
                        "name": "工具定义",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:30:33",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 53,
                        "parentId": 17,
                        "name": "工具库管理",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:30:41",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 55,
                        "parentId": 17,
                        "name": "工具维保配置",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:30:59",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 56,
                        "parentId": 17,
                        "name": "工具备件管理",
                        "type": 1,
                        "createTime": "2019-12-02 10:59:45",
                        "isDelete": 1,
                        "modifyTime": "2019-12-02 10:59:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 223,
                        "parentId": 17,
                        "name": "工具维修报告",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-04-14 10:40:07",
                        "isDelete": 1,
                        "modifyTime": "2020-04-14 10:40:07",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 19,
                "parentId": 5,
                "name": "系统管理",
                "type": 0,
                "icon": "",
                "createTime": "2019-10-08 15:20:42",
                "isDelete": 1,
                "modifyTime": "2019-11-23 11:16:45",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 59,
                        "parentId": 19,
                        "name": "部门管理",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:31:47",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 60,
                        "parentId": 19,
                        "name": "角色管理",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:31:54",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 61,
                        "parentId": 19,
                        "name": "用户管理",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:32:02",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 62,
                        "parentId": 19,
                        "name": "系统菜单",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-08 15:32:12",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 113,
                        "parentId": 19,
                        "name": "租户管理",
                        "type": 1,
                        "createTime": "2019-12-06 11:26:05",
                        "isDelete": 1,
                        "modifyTime": "2019-12-06 11:26:05",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 198,
                        "parentId": 19,
                        "name": "配置页面",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-03-18 08:53:25",
                        "isDelete": 1,
                        "modifyTime": "2020-03-18 08:53:25",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 20,
                "parentId": 5,
                "name": "条码管理",
                "type": 1,
                "createTime": "2019-12-02 19:09:05",
                "isDelete": 1,
                "modifyTime": "2019-12-02 19:09:59",
                "clientType": 0,
                "childMenu": []
            },
            {
                "id": 75,
                "parentId": 5,
                "name": "物料管理",
                "type": 0,
                "icon": "",
                "createTime": "2019-10-23 15:41:39",
                "isDelete": 1,
                "modifyTime": "2019-11-23 11:16:45",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 76,
                        "parentId": 75,
                        "name": "仓库管理",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-23 16:10:15",
                        "isDelete": 1,
                        "modifyTime": "2019-11-23 11:16:45",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 81,
                        "parentId": 75,
                        "name": "流转库存",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-10-23 16:16:51",
                        "isDelete": 1,
                        "modifyTime": "2019-12-04 14:19:06",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 82,
                        "parentId": 75,
                        "name": "库存分析",
                        "type": 1,
                        "createTime": "2019-12-02 10:06:16",
                        "isDelete": 1,
                        "modifyTime": "2019-12-02 10:06:16",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 140,
                        "parentId": 75,
                        "name": "呆滞物料",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-01-09 14:38:08",
                        "isDelete": 1,
                        "modifyTime": "2020-01-09 14:38:08",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 210,
                        "parentId": 75,
                        "name": "入库管理",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-03-26 16:54:32",
                        "isDelete": 1,
                        "modifyTime": "2020-03-26 16:54:32",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 211,
                        "parentId": 75,
                        "name": "库存明细",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-03-27 00:33:32",
                        "isDelete": 1,
                        "modifyTime": "2020-03-27 00:33:32",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 212,
                        "parentId": 75,
                        "name": "库存报表",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-03-27 00:33:40",
                        "isDelete": 1,
                        "modifyTime": "2020-03-27 00:33:40",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 213,
                        "parentId": 75,
                        "name": "出库管理",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-03-27 00:33:52",
                        "isDelete": 1,
                        "modifyTime": "2020-03-27 00:33:52",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 125,
                "parentId": 5,
                "name": "仓库管理",
                "type": 0,
                "icon": "",
                "createTime": "2019-12-24 18:37:12",
                "isDelete": 1,
                "modifyTime": "2019-12-24 18:37:12",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 126,
                        "parentId": 125,
                        "name": "入库管理",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-12-24 18:37:25",
                        "isDelete": 1,
                        "modifyTime": "2019-12-24 18:37:25",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 127,
                        "parentId": 125,
                        "name": "出库管理",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-12-25 19:04:23",
                        "isDelete": 1,
                        "modifyTime": "2019-12-25 19:04:23",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 128,
                        "parentId": 125,
                        "name": "包装条码",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-12-25 19:04:36",
                        "isDelete": 1,
                        "modifyTime": "2019-12-25 19:04:36",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 129,
                        "parentId": 125,
                        "name": "库存报表",
                        "type": 1,
                        "icon": "",
                        "createTime": "2019-12-25 19:04:48",
                        "isDelete": 1,
                        "modifyTime": "2019-12-25 19:04:48",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 136,
                        "parentId": 125,
                        "name": "多库位管理",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-01-07 13:23:06",
                        "isDelete": 1,
                        "modifyTime": "2020-01-07 13:23:06",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 141,
                        "parentId": 125,
                        "name": "库存预警",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-01-09 16:39:17",
                        "isDelete": 1,
                        "modifyTime": "2020-01-09 16:39:17",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 174,
                "parentId": 5,
                "name": "视觉数据中心",
                "type": 0,
                "icon": "",
                "createTime": "2020-02-18 15:32:51",
                "isDelete": 1,
                "modifyTime": "2020-02-18 15:32:51",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 175,
                        "parentId": 174,
                        "name": "缺陷地图",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-02-18 15:33:15",
                        "isDelete": 1,
                        "modifyTime": "2020-02-18 15:33:15",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 176,
                        "parentId": 174,
                        "name": "质检结果",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-02-18 15:33:30",
                        "isDelete": 1,
                        "modifyTime": "2020-02-18 15:33:30",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 177,
                        "parentId": 174,
                        "name": "大卷定级",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-02-18 15:33:42",
                        "isDelete": 1,
                        "modifyTime": "2020-02-18 15:33:42",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 178,
                        "parentId": 174,
                        "name": "小卷定级",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-02-18 15:34:05",
                        "isDelete": 1,
                        "modifyTime": "2020-02-18 15:34:05",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 179,
                        "parentId": 174,
                        "name": "过滤规则",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-02-18 16:37:29",
                        "isDelete": 1,
                        "modifyTime": "2020-02-18 16:37:29",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 180,
                "parentId": 5,
                "name": "知识图谱2",
                "type": 0,
                "icon": "",
                "createTime": "2020-02-19 14:13:40",
                "isDelete": 1,
                "modifyTime": "2020-02-19 14:13:40",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 182,
                        "parentId": 180,
                        "name": "物料定义",
                        "type": 0,
                        "icon": "",
                        "createTime": "2020-02-19 14:14:19",
                        "isDelete": 1,
                        "modifyTime": "2020-02-19 14:14:19",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 183,
                        "parentId": 180,
                        "name": "设备定义",
                        "type": 0,
                        "icon": "",
                        "createTime": "2020-02-19 14:14:29",
                        "isDelete": 1,
                        "modifyTime": "2020-02-19 14:14:29",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 189,
                "parentId": 5,
                "name": "基础管理",
                "type": 0,
                "icon": "",
                "createTime": "2020-03-02 10:09:08",
                "isDelete": 1,
                "modifyTime": "2020-03-02 10:09:08",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 190,
                        "parentId": 189,
                        "name": "数据字典",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-03-02 10:09:30",
                        "isDelete": 1,
                        "modifyTime": "2020-03-02 10:09:30",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 191,
                "parentId": 5,
                "name": "报表查询",
                "type": 0,
                "icon": "",
                "createTime": "2020-03-04 09:36:19",
                "isDelete": 1,
                "modifyTime": "2020-03-04 09:36:19",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 192,
                        "parentId": 191,
                        "name": "未配置物料",
                        "type": 0,
                        "icon": "",
                        "createTime": "2020-03-04 10:41:37",
                        "isDelete": 1,
                        "modifyTime": "2020-03-04 10:41:37",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 224,
                        "parentId": 191,
                        "name": "用户日志",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-04-20 15:11:42",
                        "isDelete": 1,
                        "modifyTime": "2020-04-20 15:11:42",
                        "clientType": 0,
                        "childMenu": []
                    },
                    {
                        "id": 225,
                        "parentId": 191,
                        "name": "操作日志",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-04-20 15:21:33",
                        "isDelete": 1,
                        "modifyTime": "2020-04-20 15:21:33",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 193,
                "parentId": 5,
                "name": "排程",
                "type": 0,
                "icon": "",
                "createTime": "2020-03-12 15:25:57",
                "isDelete": 1,
                "modifyTime": "2020-03-12 15:25:57",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 194,
                        "parentId": 193,
                        "name": "甘特图",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-03-12 15:58:33",
                        "isDelete": 1,
                        "modifyTime": "2020-03-12 15:58:33",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 214,
                "parentId": 5,
                "name": "标准业务对象管理",
                "type": 0,
                "icon": "",
                "createTime": "2020-03-30 17:50:24",
                "isDelete": 1,
                "modifyTime": "2020-03-30 17:50:24",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 215,
                        "parentId": 214,
                        "name": "物料",
                        "type": 1,
                        "icon": "",
                        "createTime": "2020-03-30 17:50:49",
                        "isDelete": 1,
                        "modifyTime": "2020-03-30 17:50:49",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            },
            {
                "id": 217,
                "parentId": 5,
                "name": "追溯管理",
                "type": 0,
                "icon": "",
                "createTime": "2020-04-03 14:56:59",
                "isDelete": 1,
                "modifyTime": "2020-04-03 14:56:59",
                "clientType": 0,
                "childMenu": [
                    {
                        "id": 218,
                        "parentId": 217,
                        "name": "追溯查询",
                        "type": 0,
                        "icon": "",
                        "createTime": "2020-04-03 14:57:12",
                        "isDelete": 1,
                        "modifyTime": "2020-04-03 14:57:12",
                        "clientType": 0,
                        "childMenu": []
                    }
                ]
            }
        ]
    }
}